### ISSUE TITLE
Risky Feeling for Users

### ISSUE THREAD

**Issue by the-code-karigar** [jaydeepdholakia/Tanmay-Bhat-Auto-Video-Liker#1]
Feels unreliable because system is asking for google account email and password.
Better to connect with running browser with already logged in account.

**Comment by anurag3301** [comment]
@the-code-karigar Buddy, it's totally safe. There is nothing malicious in the source code. But I'll improve it so it won't show the password as you type it.

**Comment by jaydeepdholakia** [comment]
@the-code-karigar There is nothing fishy in this code. Many other programmers can tell you by looking at the code.
