### ISSUE TITLE
About the exe file

### ISSUE THREAD

**Issue by CodeRustyPro** [jaydeepdholakia/Tanmay-Bhat-Auto-Video-Liker#10]
I wanted to ask that how do you convert python program to exe 
Is is with pyinstaller or something else please help as you helped Samay for the bot

**Comment by abhi7585** [comment]
@CodeRustyPro you can watch this [video](https://youtu.be/UZX5kH72Yx4) of TechWithTim it is helpful and works fine.

**Comment by CodeRustyPro** [comment]
Thanks buddy @abhi7585
